#!/bin/bash
# Auto-commit script with message generation
# Run after any changes to automatically commit with descriptive messages

set -e

WORKING_DIR="/home/vxm/programming/mauekspor"

cd "$WORKING_DIR"

echo "🔄 Auto-commit at $(date)"
echo ""

# Get git status
git status --short

# Check if there are changes
if [ -z "$(git status --short)" ]; then
    echo "✅ No changes to commit"
    exit 0
fi

# Generate commit message based on what changed
COMMIT_FILES=$(git diff --name-only)

# Categorize changes
TYPE=""
for file in $COMMIT_FILES; do
    if [[ $file == *"backend/app/main.py"* ]]; then
        TYPE="fix(auth): Fix login lockout time module reference"
    elif [[ $file == *"frontend/src/lib/components/VillagePotentialMap.svelte"* ]]; then
        TYPE="chore(logging): Improve error logging format"
    elif [[ $file == *"backend/.env"* ]]; then
        TYPE="config(ai): Update AI endpoint configuration"
    elif [[ $file == *".svelte" || $file == *.svelte ]] && ! [[ $file == *"test" ]]; then
        if [ -z "$TYPE" ]; then
            TYPE="feat(svelte): Update frontend component"
        fi
    elif [[ $file == *"main.py" ]] && ! [[ $file == *"/tests/" ]]; then
        TYPE="fix(py): Fix backend bug"
    elif [[ $file == *".md" ]]; then
        TYPE="docs: Update documentation"
    else
        TYPE="chore: Various improvements and fixes"
    fi
done

# Default message if not categorized
if [ -z "$TYPE" ]; then
    TYPE="chore: Auto-commit"
fi

# Add detailed description
CAT_MSG=$(cat << EOF
Detailed changes:
$(git diff --stat)

Auto-generated by build automation system.
EOF
)

# Commit
git add -A
git commit -m "$TYPE" -m "$CAT_MSG"

echo "✅ Committed: $TYPE"
echo ""

# Show log
git log --oneline -1
